version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/awscdk"
    schedule:
      interval: "weekly"
    groups:
      typescript:
        patterns:
          - "*"
        exclude-patterns:
          - "aws-cdk"
          - "aws-cdk-lib"
          - "constructs"
      awscdk:
        patterns:
          - "aws-cdk"
          - "aws-cdk-lib"
          - "constructs"
