name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run the linter
        uses: reviewdog/action-golangci-lint@db65103266f304d8ac929ad6c0cd02d14f6837ba # v2.10.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "-c ./.golangci.yaml"
          reporter: github-pr-review
