name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  octocov:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go based on the go.mod file
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "./go.mod"

      - name: Run tests with the coverage output
        run: go test -v -race -shuffle on ./app/... -coverprofile=coverage.out

      - name: Create a coverage report
        uses: k1LoW/octocov-action@b3b6ee60482a667950f87553abf1df63217235d9 # v1.5.1
        with:
          config: .octocov.yaml

  jest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "awscdk"

    steps:
      - name: Check out code into the AWS CDK directory
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: "./awscdk/package.json"
          cache: "npm"
          cache-dependency-path: "./awscdk/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with the coverage output
        run: npm test --maxWorkers=100% --watchAll=false --coverage
